dataset: wider
epochs: 50
train_batch_size: 8
eval_batch_size: 16
resize_size: 500
crop_size: 500
train_steps: 1000

anchors:
  min_iou: 0.3
  max_iou: 0.5
  sizes:
    -
    -
    - 16
    - 32
    - 64
    - 128
    - 256
    -
  ratios:
    - 0.8
  scales:
    - 1
    - 1.26
    - 1.587

loss:
  classification: focal
  localization: iou

opt:
  type: sgd
  learning_rate: 0.01
  weight_decay: 1e-4
  acc_steps: 4

  sgd:
    momentum: 0.9

sched:
  type: cosine
